### PR TITLE
Added ``--with'' param to berrybrew exec

### PR DESCRIPTION
**Pull request by stevieb9**
I've only got a bit of experience with C#, but I'm catching on. This patch allows one to Exec() on only selected installed instances instead of all of them:

> berrybrew exec --with 5.22.1_64,5.10.1_32 ...

### CODE REVIEW

**Comment by hraharahra** [comment]
I'll take a look soon. Seems useful option.

**Comment by hraharahra** [comment]
Hi @stevieb9 I really like this functionality :+1:.  Want to include it in, but won't do it in the way it is now. 
For starters, it is breaking almost every naming convention for C# :smiley:. Nothing, that can not be mended with some refactory, but look like different language.
You can find good overview of the conventions from [dofactory website](http://www.dofactory.com/reference/csharp-coding-standards) and much more extensive and authoritative information at [MSDN General Naming Conventions](https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx), and related pages. 
I have quite busy days in and out of work, so just briefly overview your code. Still couldn't get a chance to load it in IDE. I will take a more deeper look at it, and write you a e-mail to discuss with you, few points I have in mind.
Until then - Happy coding!

**Comment by stevieb9** [comment]
Thanks a lot :)

I'll review the coding style for C# in the meantime, and then you can let
me know when you're ready to discuss it all

**Comment by hraharahra** [comment]
Sorry for the delay. I will write to you later today or tomorrow at latest!

**Pull request closed without merging**
