### PR TITLE
Updated list of available archives, including LD (USE_LONG_DOUBLE) variant

### PR DESCRIPTION
**Pull request by m-ueberall**
(Taken from today's http://strawberryperl.com/releases.html listing, successfully tested using current version on Windows 10.)

### CODE REVIEW

**Comment by dnmfarrell** [comment]
Thanks for this.
@stevieb9 do you want to cherry-pick this for your upstream repo?

**Comment by stevieb9** [comment]
@dnmfarell 

Yes, I'll have a look over the coming two days. @m-ueberall can you please have a look at stevieb9/berrybrew and see what you think of that? I've got a commit bit here and I've told David that I was going to merge the projects, but I'm hesitant as I don't want to (yet) interfere with those who are still using this one.

This looks like an easy merge though, so by Friday.

**Comment by stevieb9** [comment]
Been a bit (or a lot actually) preoccupied with unexpected life events, but I've got some time now and will be focusing on this pretty hard the next few days.

**Comment by stevieb9** [comment]
In #21, I merged in the releases.json file. It does not at this time include the USE_LONG_DOUBLE variants, but allowing the user to select which cuts they want is the next work I'm going to do.

I'll have a look at what you've done here, and go from there.

**Pull request closed without merging**
